# Site settings
title: Kurt Kroeger
description: 'Production Engineer @ Facebook'
url: 'http://kwk.io/'
baseurl: '/'

author:
  name: 'Kurt Kroeger'
  email: kwkroeger -> gmail.com
  github_username:  kwkroeger
  linkedin_username:  kwkroeger

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
